### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Sothirich** [Aayush-683/BrokenDisc#10]
the bot is working fine, but i want to make a request on how to make the bot continue the song after they reconnect.
because the bots stay only for about 12 hours and i want to them to continue the song that left behind after it reconnect

**Comment by Aayush-683** [comment]
Well to do so, you will have to save the time the bot leaves the channel in a database and need to make it replay from that same exact timestamp, Its a bit tricky to work this out as the music video via it plays can differ, an alternative of this would be saving timestamp, url and channel in a database, Run a check whenever bot joins channel and continue if any music was left.

**Comment by Sothirich** [comment]
ohh thanks sir for the reply, but if you don't mind can you do the video tutorial on how to do this because im just a beginning learner 😅

**Comment by Aayush-683** [comment]
i might do it later, right now im just occupied with so much other discord bot, work and irl stuff...
You can get some help in some discord bot coding servers :D
(people are **usually** very usefull there)
