### ISSUE TITLE
Filter Reset Error

### ISSUE THREAD

**Issue by prune44** [Aayush-683/BrokenDisc#15]
when I reset filters it just shows up as an error in the console and leaves the voice channel. any solutions to this?

**Comment by Aayush-683** [comment]
whats the error?

**Comment by prune44** [comment]
> whats the error?

[ERROR]-[06.02.2022, 23:34:06]: write EPIPE

**Comment by Aayush-683** [comment]
did u change the filter values?
That error comes up when the bot is not able to understand the ffmpeg filter value

**Comment by Aayush-683** [comment]
Also since the bot itself does not have a `/filter reset` command. All you have to do is run the filter command again to reset it.

For example: Running `/8d` once will add the filter and running it again will get rid of it.

**Comment by prune44** [comment]
oh ok i tried to do what you said and it worked, thanks
