### ISSUE TITLE
Trouble when playing select videos.

### ISSUE THREAD

**Issue by fearvector** [Aayush-683/BrokenDisc#17]
I think i may have seen it on other video sources but main ones i have reproduced it on are youtube videos, this problem does not occure on all videos but so far probally around half of them. Also did a clean install to test it happens before i made any modifications to the bot.

PowerShell Output:
![image](https://user-images.githubusercontent.com/36361597/156753139-97d03f23-989f-4ae5-a0b8-5a212af975d9.png)

Discord Output:
![image](https://user-images.githubusercontent.com/36361597/156753289-c6e19b39-9c31-4e38-bbff-8d16af43de19.png)

**Comment by stvev1337** [comment]
I can, uhh, also confirm this. As well as some other issues.

**Comment by Aayush-683** [comment]
this issue is with discord bot caching its interactions. Im looking into how to get this fixed as of now

**Comment by GeekHamza1** [comment]
any soulution for this
