### ISSUE TITLE
Error Code 429

### ISSUE THREAD

**Issue by explorehost** [Aayush-683/BrokenDisc#3]
Why is my bot showing @discordusername Status code: 429

**Comment by Aayush-683** [comment]
thats an error on your hosting providers behalf, it means rate limitations have occured due to sending frequent music requests repeatedly

**Comment by explorehost** [comment]
Oh. I will contact replit. Is there anyway to avoid this?

**Comment by Aayush-683** [comment]
Not really, its due to the low cpu hardware that repl.it provides :P
