### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by blaze-blitz** [Aayush-683/BrokenDisc#7]
404

**Comment by Aayush-683** [comment]
can you explain the issue further?

**Comment by blaze-blitz** [comment]
@BlackKnight683 The Bot Is Sending 404 Doesn't Play Music

**Comment by Aayush-683** [comment]
check your api key, if regenerationg doesnt help try using a diff google account, google might have banned your api key cus of "abuse"

**Comment by Aayush-683** [comment]
contact support if they actually did

**Comment by Aayush-683** [comment]
check #8

**Comment by blaze-blitz** [comment]
Google Doesn't Banned My Api

**Comment by blaze-blitz** [comment]
I Created New Api
